name: beacon_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.35.5
#  flutter_local_notifications: ^19.4.0
#  firebase_core: ^4.0.0
  permission_handler: ^12.0.1
#  firebase_database: ^12.0.0
  minew_beacon_plus_flutter: ^0.0.3
  flutter_ble_peripheral: ^1.2.6


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
